name: Dependabot Updates

on:
  schedule:
    - cron: '0 7 * * 1'  # Run at 7 AM UTC on Monday
  workflow_dispatch:     # Allow manual triggering
  push:
    paths:
      - 'requirements.txt'
      - '.github/dependabot.yml'
      - 'Dockerfile'

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Dependabot
        uses: github/dependabot-action@main
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"