name: Update pip and dependencies

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
  workflow_dispatch:     # Allow manual triggering

jobs:
  update-pip:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Update pip
        run: |
          python -m pip install --upgrade pip
          pip --version
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-test.txt
          
      - name: Run safety scan
        run: |
          pip install safety
          safety scan -r requirements.txt -r requirements-test.txt